--- 
- name: "Create groups on AIX"
  hosts:  Sean_Test_AIX
  collections:
  - ibm.power_aix
  tasks:

  - name: Create joker group
    group:
      state: present
      name: joker
      group_attributes: 'id=1182'
